# Numpy: Assignment 1

# Write a function so that the columns of the output matrix are powers of the input vector.

Write a function so that the columns of the output matrix are powers of
the input vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

In [6]:
import numpy as np
x = np.array([1,2,3,4])
n = len(x)
np.vander(x,n)

array([[ 1,  1,  1,  1],
       [ 8,  4,  2,  1],
       [27,  9,  3,  1],
       [64, 16,  4,  1]])

In [7]:
np.vander(x, increasing = True)

array([[ 1,  1,  1,  1],
       [ 1,  2,  4,  8],
       [ 1,  3,  9, 27],
       [ 1,  4, 16, 64]])

In [8]:
np.column_stack([x**(n-i-1) for i in range(n)])

array([[ 1,  1,  1,  1],
       [ 8,  4,  2,  1],
       [27,  9,  3,  1],
       [64, 16,  4,  1]], dtype=int32)

# Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of the given sequence is defined as follows:
The moving average sequence has n-k+1 elements as shown below.

In [1]:
# Write a function to find moving average in an array over a window:
#Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [2]:
import numpy as np
n = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
k = 4
npArray1 = np.array(n)

In [3]:
def movingAverage(array1, AverageSize):
    size = array1.shape[0]-AverageSize
    emptyArray1 = np.empty(size)
    
    for i in range(size):
        emptyArray1[i] = npArray1[i:i+AverageSize].sum()
    return emptyArray1

In [4]:

movingAverage(npArray1, k)

array([100., 140., 180., 220., 260., 300.])

In [5]:
print('Output for testing purpose: ')
npArray12 = np.array([3,5,7,2,8,10,11,65,72,81,99,100,150])
movingAverage(npArray12, 3)

Output for testing purpose: 


array([ 60.,  90., 120., 150., 180., 210., 240., 270., 190., 100.])